### PR TITLE
[#2824916] Give support for entity_reference_revisions field type

### PR DESCRIPTION
**Pull request by plopesc**
Hello,

I was trying to create paragraphs items using this module, but I was not able, given that entity_reference_revisions field type was not supported.

Adding the change below, it's possible to import paragraph items.

Thanks

PS: RElated to d.o issue https://www.drupal.org/node/2824916

### CODE REVIEW

**Comment by pakmanlh** [comment]
Im trying to implement the paragraph default content generation to reference from an entityreference field and I got this error:

PHP Fatal error:  Call to a member function getRevisionId() on null in /Sites/bla/web/modules/contrib/entity_reference_revisions/src/Plugin/Field/FieldType/EntityReferenceRevisionsItem.php on line 213

I don't see how it should be reference from a entity reference field to a paragraph revision…

Could you please give a code example for this situation?

Thank you very much @plopesc !

**Comment by plopesc** [comment]
Thanks @pakmanlh 

What I did:
1. Create a paragraph bundle
2. Create a "Entity reference revisions" field type in my custom block type called "field_slide"
3. Add these migration files:

block_content.rotating_banner.csv
```
info,field_slide,uuid
Main Rotating Banner,"[\"Slide 1\",\"Slide 2\"]",d9276d33-4bd4-492d-9631-b92c9bc8bfbc
```
paragraph.rotating_banner_item.csv
```
field_title,field_caption,field_imageTarget_id,field_imageAlt,field_linkTitle,field_linkUri,field_video,parent_id,parent_type,parent_field_name
Slide 1,Caption 1,druplicon_large.png,Druplicon,Learn More,internal:/page/about,,1,block_content,field_slide,
```

My project versions:
- Drupal core: 8.2.2
- Paragraphs: 8.x-1.0
- Entity Reference Revisions: 8.x-1.0

In any case, we can connect on IRC and I can show you my local configuration.

Thanks!

**Comment by pakmanlh** [comment]
Now I see! You also add the parent_type, parent_id and parent_field_name to the paragraph migration, that's what I missed 😄 

Thank you again!

**Comment by rodrigoaguilera** [comment]
@plopesc  Can you add that code example to example_default_content dir?

**Comment by plopesc** [comment]
Sure thing!
I'll adapt my content to the rest of the example.
PR coming soon ;)

**Comment by plopesc** [comment]
@pakmanlh @rodrigoaguilera I simplified a bit my migration files to make them more readable by end users.
However, these migrations won't work out of the box because the block_content type and the paragraph bundle are not defined. But I think that it's a good example of a more complex use case of this great module.

Thanks!

**Comment by rodrigoaguilera** [comment]
Few examples work without some configuration, It is fine.
I still don't get why the "1" for parent_id but I have seen this patch working and we can fix that later.

Thank you!

**Pull request merged**
