### PR TITLE
Add support for migrating entity revisions

### PR DESCRIPTION
**Pull request by tstoeckler**
I'm using entity reference revisions and I don't want to explicitly reference ID and revision ID in the content. So just like for the `target_id` entity references this module currently sets up a migration I want to set up a similar migration for the `target_revision_id` of entity reference revisions. However, for that to work the module first has to provide such migrations in the first place. That is what this patch does.

For revisionable entity types, a `$entity_type_id . '_revision'` migration is automatically provided on top of the non-revision one. The revision one uses the first one as the source for the ID. That allows using the second migration as source for the `target_revision_id` property.

It also sets up this migration for entity reference fields.

Example usage:
```yaml
# ../default_content/node.article.yml
-
  title: 'Example page'
  field_paragraphsTarget_revision_id: 77152a7c-e331-43ea-a927-6fd687831368

# ../default_content/paragraph.text.yml
-
  uuid: 77152a7c-e331-43ea-a927-6fd687831368
  field_textValue: 'Example paragraph text'
  field_textFormat: basic_html
```

Edit: fix some unnecessary nesting in example yml
Edit2: Actually describe behavior correctly. (I had to change this around a bunch of times before it worked, sorry...)
Edit3: Updated again to match new behavior.

### CODE REVIEW

**Comment by tstoeckler** [comment]
I just realized I only need the iterator plugin because the field is multiple, i.e. that basically works around #21

**Comment by tstoeckler** [comment]
Updated the comment above for the new usage. Now overrides are no longer necessary. I'm actually using this locally with multiple values, as well, see https://github.com/tstoeckler/migrate_default_content/tree/dev-entity-revisions-multiple for that. I will try to fix the multiple value issue independently, though, over at #21 

This should be ready for review now.

**Comment by rodrigoaguilera** [comment]
I just did a quick review of just the code and it looks good.

I'll try to test it more next week to merge the request if no one steps up first.

**Comment by rodrigoaguilera** [comment]
I tested this code manually and I was not able to make it work.

I think is because the field expects two subvalues target_id and target_revision_id and we only provide one.

Anyway the concept of creating revision migrations when are not actually creating a new revisions for the content entities seems weird. The dependency for the revision migrations on their parent migrations is also missing.

I feel is better to keep the data files clean so we dont have to specify target_id and target_revision_id and we can treat them transparently as if they were entity reference fields.

I will make a different PR soon.

**Pull request closed without merging**
